name = "simple_tcp_ping"
[defaults]
builder = "docker:generic"
runner = "local:docker"

[builders."docker:generic"]
enabled = true

[runners."local:docker"]
enabled = true

[[testcases]]
name= "simple_tcp_ping"
instances = { min = 2, default = 2, max = 2 }
